Login/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = "Login"
urlpatterns = [
    url('^$',views.Login,name='Login'),
    url('^login$',views.Verify,name='verify_login'),
    url('^register$',views.Register,name='Register'),
    url('^logout$',views.Logout,name='Logout'),
    url('^user_details/(?P<username>[\w\-]+)$',views.user_details,name='User_Details'),
    url('^user_det$',views.user_det,name='User_Det'),
    url('^question_responses$',views.question_res,name='question_responses'),
    url('^Most_Compatible$',views.Most_Compatible,name='Most_Compatible'),
]

The_Perfect_Match/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('Login.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Login/models.py
from django.db import models
from django.contrib.auth.models import User

class User_Male(models.Model):
    basic_details = models.OneToOneField(User,unique = True,on_delete=models.CASCADE)
    mobile_number = models.IntegerField()
    date_of_birth = models.DateField()
    profile_picture = models.FileField()
    premium_user = models.BooleanField(default=False)

class User_Female(models.Model):
    basic_details = models.OneToOneField(User,unique = True,on_delete=models.CASCADE)
    mobile_number = models.IntegerField()
    date_of_birth = models.DateField()
    profile_picture = models.FileField()
    premium_user = models.BooleanField(default = False)

class question_responses(models.Model):
    basic_details = models.OneToOneField(User,on_delete=models.CASCADE)
    question1 = models.CharField(max_length=3)
    question2 = models.CharField(max_length=3)
    question3 = models.CharField(max_length=3)
    question4 = models.CharField(max_length=3)
    question5 = models.CharField(max_length=3)

Login/views.py
from django.shortcuts import render,HttpResponse, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from .models import User_Male,User_Female,question_responses
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def Login(request):
    if request.user.is_authenticated():
        user_details = User_Male.objects.filter(basic_details = request.user)
        if len(user_details) == 0:
            user_details = User_Female.objects.filter(basic_details = request.user)
            all_users = User_Male.objects.all()
        else:
            all_users = User_Female.objects.all()
        return render(request,"Login/main.html",{"user":request.user,"user_details":user_details[0],"all_users":all_users})
    else:
        return render(request,'Login/Login.html',{})

@csrf_exempt
def Verify(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        gender = request.POST['gender']
        user = authenticate(username = username,password = password)
        if user is not None:
            if user.is_active:
                login(request,user)
                user_details = User_Male.objects.filter(basic_details = request.user)
                if len(user_details) == 0:
                    user_details = User_Female.objects.filter(basic_details = request.user)
                    all_users = User_Male.objects.all()
                else:
                    all_users = User_Female.objects.all()
                return render(request,"Login/main.html",{"user":user,"user_details":user_details[0],"all_users":all_users})
        else:
            return redirect("/")
    else:
        return redirect("/")

@csrf_exempt
def Register(request):
    if request.method == 'POST':
        if (User.objects.filter(username = request.POST['uname'])).exists():
            return redirect("Login:Login")
        else:
            user = User.objects.create_user(username = request.POST['uname'],password=request.POST['password'],email = request.POST['email'])
            user.first_name = request.POST['fname']
            user.last_name = request.POST['lname']
            user.save()
            if (request.POST['gender'] == "male"):
                d = (request.POST['dob']).split("-")
                date = d[0]+"-"+d[1]+"-"+d[2]
                new_u = User_Male(basic_details = user,mobile_number = int(request.POST['m_no']),date_of_birth = date,profile_picture = request.FILES['profile_pic'])
                if (request.POST['premium'] == "yes"):
                    new_u.premium_user = True
                else:
                    new_u.premium_user = False
                new_u.save()
                return render(request,"Login/questions.html",{"user":user})
            else:
                d = (request.POST['dob']).split("-")
                date = d[0]+"-"+d[1]+"-"+d[2]
                new_u = User_Female(basic_details = user,mobile_number = int(request.POST['m_no']),date_of_birth = date,profile_picture = request.FILES['profile_pic'])
                if (request.POST['premium'] == "yes"):
                    new_u.premium_user = True
                else:
                    new_u.premium_user = False
                new_u.save()
                return render(request,"Login/questions.html",{"user":user})
    else:
        return redirect('/')

def Logout(request):
    if request.user.is_authenticated():
        logout(request)
        return redirect("Login:Login")
    else:
        return redirect("Login:Login")

def user_details(request,username):
    if request.user.is_authenticated():
        use = User.objects.get(username = username)
        user_details = User_Male.objects.filter(basic_details = use)
        u = User_Male.objects.filter(basic_details = request.user)
        if len(user_details) == 0:
            user_details = User_Female.objects.filter(basic_details = use)
        if len(u) == 0:
            u = User_Female.objects.filter(basic_details = request.user)
        return render(request,'Login/user_details.html',{"user_det":user_details[0],"user":request.user,"user_details":u[0],"question_responses":question_responses.objects.get(basic_details = use)})
    else:
        return redirect("/")

@csrf_exempt
def user_det(request):
    if request.user.is_authenticated():
        if request.method == "POST":
            username = request.POST["q"]
            try:
                user = User.objects.get(username = username)
            except User.DoesNotExist:
                return HttpResponse("<h1>"+"No Such User"+"<br>"+"Please Go back and Check the Spelling"+"</h1>")
            user_details = User_Male.objects.filter(basic_details = user)
            u = User_Male.objects.filter(basic_details = request.user)
            if len(user_details) == 0:
                user_details = User_Female.objects.filter(basic_details = request.user)
            if len(u) == 0:
                u = User_Female.objects.filter(basic_details = request.user)
            return render(request,'Login/user_details.html',{"user_det":user_details[0],"user":request.user,"user_details":u[0],"question_responses":question_responses.objects.get(basic_details = user)})
        else:
            return redirect("/")
    else:
        return redirect("/")

@csrf_exempt
def question_res(request):
    if request.method == "POST":
        username = request.POST['name']
        user = User.objects.get(username = username)
        response = question_responses(basic_details = user)
        response.question1 = request.POST['question1']
        response.question2 = request.POST['question2']
        response.question3 = request.POST['question3']
        response.question4 = request.POST['question4']
        response.question5 = request.POST['question5']
        response.save()
        return redirect("/")
    else:
        return redirect("/")

def Most_Compatible(request):
    if request.user.is_authenticated():
        user_details = User_Male.objects.filter(basic_details = request.user)
        if len(user_details) == 0:
            user_details = User_Female.objects.filter(basic_details = request.user)
            all_users = User_Male.objects.all()
        else:
            all_users = User_Female.objects.all()
        return render(request,"Login/Most_Compatible.html",{"user":request.user,"user_details":user_details[0],"all_users":all_users})
    else:
        return redirect("/")

Login/templates/Login/Login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Login/Bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Login/Bootstrap/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Login/custum.css' %}">
    <link rel="image" type="image" href="{% static 'Login/images/map.png' %}">
    <title>Login</title>
  </head>
  <body>
    <div class="jumbotron" style="background-color:#FF6600;margin-bottom: 0px;opacity:.8">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <h1 style="font-size:35px;font-family:serif!important;color:#fff">
              <center>THE<br><strong>PERFECT<br>MATCH</strong></center>
            </h1>
          </div>
          <div class="col-sm-6">
            <center>
              <form action="{% url 'Login:verify_login' %}" method="post" style="margin-top:30px">
                <div class="form-inline" style="margin-bottom:10px">
                  <label for="username" style="color:#fff;margin-right:5px">UserName</label>
                  <input type="text" name="username" placeholder="User Name" class="form-control" style="border-radius: 2px;" required>
                </div>
                <div class="form-inline" style="margin-bottom:15px">
                  <label for="pwd" style="color:#fff;margin-right:5px">Password</label>
                  <input type="password" name="password" placeholder="Password" class="form-control" style="border-radius: 5px;" required>
                </div>
                <div class="form-inline" style="margin-bottom:10px">
                  <label for="gender" style="color:black;width:120px">Gender</label>
                    <div class="checkbox">
                      <label><input type="radio" value="male" name="gender" required>Male</label>
                    </div>
                    <div class="checkbox">
                      <label><input type="radio" value="female" name="gender" required>Female</label>
                    </div>
                </div>
                <button type="submit" name="submit" class="btn btn-primary btn-md" style="border-radius: 5px;" aria-label="left-align">Login
                  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                </button>
              </form>
            </center>
          </div>
        </div>
      </div>
    </div>
    <div class="login_bottom">
      <div class="container" style="font-size:15px">
        <!-- Block should come here -->
        <div class="row"  style="margin-top:30px">
          <div class="col-sm-5 col-sm-offset-7">
            <form action="{% url 'Login:Register' %}" method="post" enctype='multipart/form-data'>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="email" style="color:black;width:120px">Email-Id</label>
                <input type="email" name="email" placeholder="Email-Id" class="form-control" style="border-radius: 2px" required>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="username" style="color:black;width:120px">User Name</label>
                <input type="text" name="uname" placeholder="User Name" class="form-control" style="border-radius: 2px" required>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="username" style="color:black;width:120px">Password</label>
                <input type="password" name="pass" placeholder="Password" class="form-control" style="border-radius: 2px" required>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="password_again" style="color:black;width:120px">Password(again)</label>
                <input type="password" name="password" placeholder="Password(again)" class="form-control" style="border-radius: 2px" required>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="FirstName" style="color:black;width:120px">First Name</label>
                <input type="text" name="fname" placeholder="First Name" class="form-control" style="border-radius: 2px" required>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="LastName" style="color:black;width:120px">Last Name</label>
                <input type="text" name="lname" placeholder="Last Name" class="form-control" style="border-radius: 2px" required>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="mobile_number" style="color:black;width:120px">Mobile Number</label>
                <input type="text" name="m_no" placeholder="Mobile Number" class="form-control" style="border-radius: 2px" required>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="date_of_birth" style="color:black;width:120px">Date Of Birth</label>
                <input type="date" name="dob" placeholder="YYYY-MM-DD" class="form-control" style="border-radius: 2px" required>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="profile_picture" style="color:black;width:120px">Profile Picture</label>
                <label class="btn btn-default btn-file">Browse <input type="file" style="border-radius: 2px;" name = "profile_pic" required></label>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="gender" style="color:black;width:120px">Gender</label>
                  <div class="checkbox">
                    <label><input type="radio" value="male" name="gender">Male</label>
                  </div>
                  <div class="checkbox">
                    <label><input type="radio" value="female" name="gender">Female</label>
                  </div>
              </div>
              <div class="form-inline" style="margin-bottom:10px">
                <label for="premium_user" style="color:black;width:120px">Want to be a premium user</label>
                  <div class="checkbox">
                    <label><input type="radio" value="yes" name="premium">Yes</label>
                  </div>
                  <div class="checkbox">
                    <label><input type="radio" value="no" name="premium">No</label>
                  </div>
              </div>
              <center>
                <button type="submit" name="submit" class="btn btn-primary btn-md" style="border-radius: 5px;" aria-label="left-align">Register
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                </button>
              </center>
            </form>
            <br><br><br>
          </div>
        </div>
      </div>
    </div>
</html>

Login/templates/Login/Most_Compatible.html
{% extends "Login/base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="albums-container container-fluid" style="margin-left:20px;margin-right-20px">

  <!-- Albums -->
  <div class="row">
      <div class="col-sm-12">
          <h3 style="text-justify:centre">Most Compatible Based On Your Requirements</h3>
      </div>
      {% for users in all_users %}
          {% if user_details.premium_user %}
            <a href="/user_details/{{users.basic_details.username}}">
              <div class="col-sm-4 col-lg-2">
                  <div class="thumbnail" style="background-color:#ff9933;opacity:1">
                      <img src="{{ users.profile_picture.url }}" class="img-circle" style="margin-top:10px;height:200px">
                      <div class="caption" style="margin-bottom:5px">
                          <h3>{{ users.basic_details.first_name }} {{ users.basic_details.last_name }}</h3>
                          <h5>DOB: {{users.date_of_birth}}</h5>
                      </div>
                  </div>
              </div>
            </a>
          {% else %}
            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail" style="background-color:#ff9933;opacity:1">
                    <img src="{{ users.profile_picture.url }}" class="img-circle" style="margin-top:10px">
                    <div class="caption" style="margin-bottom:5px">
                        <h3>{{ users.basic_details.first_name }} {{ users.basic_details.last_name }}</h3>
                        <h5>DOB: {{users.date_of_birth}}</h5>
                    </div>
                </div>
            </div>
          {% endif %}
      {% endfor %}
    </div>
</div>
{% endblock %}

Login/templates/Login/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Home{% endblock %}</title>
	{% load staticfiles %}
	<link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-inverse" style="background-color:#FF6600;margin-bottom: 0px;opacity:.8">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<img src="{{ user_details.profile_picture.url }}" alt="profile picture" width="40px" class="img-circle" style="margin-top:5px">
			<a class="navbar-brand" href="{% url 'Login:Login' %}" style="color:#fff;font-family:serif!important">{{ user.username }}</a>
		</div>
		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav" style="margin-left:20px">
				<li class="">
					<a href="/Most_Compatible" style="color:#fff">
						<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>&nbsp;
						Most Compatible
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" method="post" action="/user_det" style="margin-left:50px">
				<div class="form-group">
					<input type="text" class="form-control" name="q" placeholder="Search USERNAME">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="#" style="color:#fff">
						<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;
						Edit Personal Details
					</a>
				</li>
				<li class="">
					<a href="{% url 'Login:Logout' %}" style="color:#fff">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
						Logout
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Login/templates/Login/main.html
{% extends "Login/base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="albums-container container-fluid" style="margin-left:20px;margin-right-20px">

  <!-- Albums -->
  <div class="row">
      <div class="col-sm-12">
          <h3 style="text-justify:centre">All Possible Matches</h3>
      </div>
      {% for users in all_users %}
          {% if user_details.premium_user %}
            <a href="/user_details/{{users.basic_details.username}}">
              <div class="col-sm-4 col-lg-2">
                  <div class="thumbnail" style="background-color:#ff9933;opacity:1">
                      <img src="{{ users.profile_picture.url }}" class="img-circle" style="margin-top:10px;height:200px">
                      <div class="caption" style="margin-bottom:5px">
                          <h3>{{ users.basic_details.first_name }} {{ users.basic_details.last_name }}</h3>
                          <h5>DOB: {{users.date_of_birth}}</h5>
                      </div>
                  </div>
              </div>
            </a>
          {% else %}
            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail" style="background-color:#ff9933;opacity:1">
                    <img src="{{ users.profile_picture.url }}" class="img-circle" style="margin-top:10px">
                    <div class="caption" style="margin-bottom:5px">
                        <h3>{{ users.basic_details.first_name }} {{ users.basic_details.last_name }}</h3>
                        <h5>DOB: {{users.date_of_birth}}</h5>
                    </div>
                </div>
            </div>
          {% endif %}
      {% endfor %}
    </div>
</div>
{% endblock %}

Login/templates/Login/questions.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Questions</title>
  </head>
  <body>
    <div class="jumbotron" style="background-color:#FF6600;margin-bottom: 0px;opacity:.8">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <center>
                <h1>Please answer these basic questions</h1>
            </center>
          </div>
        </div>
      </div>
    </div>
    <form action="/question_responses" method="post">
      <div class="container">
        <input type="radio" name="username" value="{{user.username}}" checked="true" hidden="true">
        <div class="row" style="margin-left:100px">
          <div class="col-xs-12">
            <h2>Do you like pets?</h2>
          </div>
          <div class="col-xs-12">
            <div class="checkbox-inline">
              <label><input type="radio" value="no" name="question1">NO</label>
              <label><input type="radio" value="yes" name="question1">YES</label>
            </div>
          </div>
        </div>
        <div class="row" style="margin-left:100px">
          <div class="col-xs-12">
            <h2>Do you like reading books?</h2>
          </div>
          <div class="col-xs-12">
            <div class="checkbox-inline">
              <label><input type="radio" value="no" name="question2">NO</label>
              <label><input type="radio" value="yes" name="question2">YES</label>
            </div>
          </div>
        </div>
        <div class="row" style="margin-left:100px">
          <div class="col-xs-12">
            <h2>Do you smoke or drink?</h2>
          </div>
          <div class="col-xs-12">
            <div class="checkbox-inline">
              <label><input type="radio" value="no" name="question3">NO</label>
              <label><input type="radio" value="yes" name="question3">YES</label>
            </div>
          </div>
        </div>
        <div class="row" style="margin-left:100px">
          <div class="col-xs-12">
            <h2>Do you like partying?</h2>
          </div>
          <div class="col-xs-12">
            <div class="checkbox-inline">
              <label><input type="radio" value="no" name="question4">NO</label>
              <label><input type="radio" value="yes" name="question4">YES</label>
            </div>
          </div>
        </div>
        <div class="row" style="margin-left:100px">
          <div class="col-xs-12">
            <h2>Do you travel or not?</h2>
          </div>
          <div class="col-xs-12">
            <div class="checkbox-inline">
              <label><input type="radio" value="no" name="question5">NO</label>
              <label><input type="radio" value="yes" name="question5">YES</label>
            </div>
          </div>
        </div>
        <button type="submit" name="button">Submit</button>
      </div>
    </form>
  </body>
</html>

Login/templates/Login/user_details.html
{% extends "Login/base.html" %}
{% block title %}{{user_det.basic_details.username}}{% endblock %}
{% block body %}
  <div class="container">
    <div class="row">
          <div class="profile-header-container">
            <div class="profile-header-img" style="margin-left:44%;margin-top:50px">
                    <img class="img-circle" src="{{user_det.profile_picture.url}}" style="margin-top:10px;height:200px"/>
                    <!-- badge -->
                    <div class="rank-label-container">
                        <span class="label label-default rank-label">{{user_det.basic_details.first_name}} {{user_det.basic_details.last_name}}</span>
                    </div>
            </div>
            <div style="margin-top20px">
              <h3 style="text-align:center">{{user_det.basic_details.email}}</h3>
              <h3 style="text-align:center">{{user_det.mobile_number}}</h3>
            </div>
            <div style="margin-top20px;background-color:orange;margin-left:25%;margin-right:25%">
              <h1 style="text-align:center">Matches Preferences</h1>
              <h3 style="text-align:center">Likes Pets:{{ question_responses.question1 }}</h3>
              <h3 style="text-align:center">Loves Reading Books:{{ question_responses.question2 }}</h3>
              <h3 style="text-align:center">Smoking and drinking:{{ question_responses.question3 }}</h3>
              <h3 style="text-align:center">Loves to party:{{ question_responses.question4 }}</h3>
              <h3 style="text-align:center">Loves Travelling:{{ question_responses.question5 }}</h3>
            </div>
    </div>
  </div>
{% endblock %}